---
name: "HAOS Kiosk Display"
description: "Minimal Xorg + luakit browser kiosk for Home Assistant touchscreen display"
version: "1.4.0"
slug: "haoskiosk"
url: https://github.com/mykosmid/haos_kiosk/tree/main/haoskiosk

arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386

startup: application
host_network: true
init: false
ingress: true
homeassistant_api: true
auth_api: true
usb: true

ulimits:
  nofile:
    soft: 65536
    hard: 65536

devices:
  - /dev/dri/card0
  - /dev/dri/card1
  - /dev/dri/renderD128
  - /dev/input/event0
  - /dev/input/event1
  - /dev/input/event2
  - /dev/input/event3
  - /dev/input/event4
  - /dev/input/event5
  - /dev/input/event6
  - /dev/input/event7
  - /dev/input/event8
  - /dev/input/event9
  - /dev/input/event10
  - /dev/input/event11
  - /dev/input/event12
  - /dev/input/event13
  - /dev/input/event14
  - /dev/input/event15
  - /dev/input/event16
  - /dev/input/event17
  - /dev/input/event18
  - /dev/input/event19
  - /dev/input/event20
  - /dev/input/event21
  - /dev/input/event22
  - /dev/input/event23
  - /dev/input/event24
  - /dev/input/event25

map:
  - addon_config:rw
  - media:rw

privileged:
  - SYS_ADMIN

options:
  ha_url: "http://localhost:8123"
  ha_dashboard: ""
  login_delay: 1.0
  browser_refresh: 600
  screen_timeout: 0
  output_number: 1
  rotate_display: "normal"
  map_touch_inputs: true
  keyboard_layout: us
  debug_mode: false
  screensaver_enabled: false
  screensaver_timeout: 300
  screensaver_interval: 15
  screensaver_media_folder: "screensaver"
  screensaver_source_folder: ""
  screensaver_resize_width: 1920
  screensaver_resize_height: 1080

schema:
  ha_username: str
  ha_password: password
  ha_url: str
  ha_dashboard: str?
  login_delay: float(0,)
  browser_refresh: int(0,)
  screen_timeout: int(0,)
  output_number: int(1,2)
  rotate_display: list(normal|left|right|inverted)
  map_touch_inputs: bool
  keyboard_layout: str
  debug_mode: bool
  screensaver_enabled: bool
  screensaver_timeout: int(1,)
  screensaver_interval: int(1,)
  screensaver_media_folder: str
  screensaver_source_folder: str
  screensaver_resize_width: int(1,)
  screensaver_resize_height: int(1,)

translations:
  - en

environment:
  DISPLAY: ":0"
